### PR TITLE
remove obsolete flag from helm init command

### PR DESCRIPTION
**Pull request by balintbekefi**
--client-only is no longer needed and no longer supported in Helm 3

### CODE REVIEW

**Comment by balintbekefi** [comment]
Since this uses helm 2, seems like the test won't pass... However, master as it currently stands doesn't work with helm 3.

**Comment by remmeier** [comment]
maybe a feature flag in HelmExtension to enable v3 support?

**Comment by balintbekefi** [comment]
> maybe a feature flag in HelmExtension to enable v3 support?

Sounds good! Wanna do it or should I?

**Comment by remmeier** [comment]
thx, new version available as soon as https://travis-ci.org/rmee/gradle-plugins finished (version number available in the publish section of the log output)

**Pull request merged**
